// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parameters.proto

#ifndef PROTOBUF_parameters_2eproto__INCLUDED
#define PROTOBUF_parameters_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace protbuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_parameters_2eproto();
void protobuf_AssignDesc_parameters_2eproto();
void protobuf_ShutdownFile_parameters_2eproto();

class ParameterBasicInformation;
class Parameter;
class resParameters;

// ===================================================================

class ParameterBasicInformation : public ::google::protobuf::MessageLite {
 public:
  ParameterBasicInformation();
  virtual ~ParameterBasicInformation();

  ParameterBasicInformation(const ParameterBasicInformation& from);

  inline ParameterBasicInformation& operator=(const ParameterBasicInformation& from) {
    CopyFrom(from);
    return *this;
  }

  static const ParameterBasicInformation& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const ParameterBasicInformation* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(ParameterBasicInformation* other);

  // implements Message ----------------------------------------------

  ParameterBasicInformation* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ParameterBasicInformation& from);
  void MergeFrom(const ParameterBasicInformation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:protbuf.ParameterBasicInformation)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::uint32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_parameters_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_parameters_2eproto();
  #endif
  friend void protobuf_AssignDesc_parameters_2eproto();
  friend void protobuf_ShutdownFile_parameters_2eproto();

  void InitAsDefaultInstance();
  static ParameterBasicInformation* default_instance_;
};
// -------------------------------------------------------------------

class Parameter : public ::google::protobuf::MessageLite {
 public:
  Parameter();
  virtual ~Parameter();

  Parameter(const Parameter& from);

  inline Parameter& operator=(const Parameter& from) {
    CopyFrom(from);
    return *this;
  }

  static const Parameter& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const Parameter* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(Parameter* other);

  // implements Message ----------------------------------------------

  Parameter* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Parameter& from);
  void MergeFrom(const Parameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required bytes configData = 3;
  inline bool has_configdata() const;
  inline void clear_configdata();
  static const int kConfigDataFieldNumber = 3;
  inline const ::std::string& configdata() const;
  inline void set_configdata(const ::std::string& value);
  inline void set_configdata(const char* value);
  inline void set_configdata(const void* value, size_t size);
  inline ::std::string* mutable_configdata();
  inline ::std::string* release_configdata();
  inline void set_allocated_configdata(::std::string* configdata);

  // @@protoc_insertion_point(class_scope:protbuf.Parameter)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_configdata();
  inline void clear_has_configdata();

  ::std::string* name_;
  ::std::string* configdata_;
  ::google::protobuf::uint32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_parameters_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_parameters_2eproto();
  #endif
  friend void protobuf_AssignDesc_parameters_2eproto();
  friend void protobuf_ShutdownFile_parameters_2eproto();

  void InitAsDefaultInstance();
  static Parameter* default_instance_;
};
// -------------------------------------------------------------------

class resParameters : public ::google::protobuf::MessageLite {
 public:
  resParameters();
  virtual ~resParameters();

  resParameters(const resParameters& from);

  inline resParameters& operator=(const resParameters& from) {
    CopyFrom(from);
    return *this;
  }

  static const resParameters& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const resParameters* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(resParameters* other);

  // implements Message ----------------------------------------------

  resParameters* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const resParameters& from);
  void MergeFrom(const resParameters& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .protbuf.Parameter parameters = 1;
  inline int parameters_size() const;
  inline void clear_parameters();
  static const int kParametersFieldNumber = 1;
  inline const ::protbuf::Parameter& parameters(int index) const;
  inline ::protbuf::Parameter* mutable_parameters(int index);
  inline ::protbuf::Parameter* add_parameters();
  inline const ::google::protobuf::RepeatedPtrField< ::protbuf::Parameter >&
      parameters() const;
  inline ::google::protobuf::RepeatedPtrField< ::protbuf::Parameter >*
      mutable_parameters();

  // @@protoc_insertion_point(class_scope:protbuf.resParameters)
 private:

  ::google::protobuf::RepeatedPtrField< ::protbuf::Parameter > parameters_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_parameters_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_parameters_2eproto();
  #endif
  friend void protobuf_AssignDesc_parameters_2eproto();
  friend void protobuf_ShutdownFile_parameters_2eproto();

  void InitAsDefaultInstance();
  static resParameters* default_instance_;
};
// ===================================================================


// ===================================================================

// ParameterBasicInformation

// required uint32 id = 1;
inline bool ParameterBasicInformation::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParameterBasicInformation::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParameterBasicInformation::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParameterBasicInformation::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 ParameterBasicInformation::id() const {
  return id_;
}
inline void ParameterBasicInformation::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// Parameter

// required uint32 id = 1;
inline bool Parameter::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Parameter::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Parameter::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Parameter::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Parameter::id() const {
  return id_;
}
inline void Parameter::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required string name = 2;
inline bool Parameter::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Parameter::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Parameter::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Parameter::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Parameter::name() const {
  return *name_;
}
inline void Parameter::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Parameter::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Parameter::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Parameter::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Parameter::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Parameter::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes configData = 3;
inline bool Parameter::has_configdata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Parameter::set_has_configdata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Parameter::clear_has_configdata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Parameter::clear_configdata() {
  if (configdata_ != &::google::protobuf::internal::kEmptyString) {
    configdata_->clear();
  }
  clear_has_configdata();
}
inline const ::std::string& Parameter::configdata() const {
  return *configdata_;
}
inline void Parameter::set_configdata(const ::std::string& value) {
  set_has_configdata();
  if (configdata_ == &::google::protobuf::internal::kEmptyString) {
    configdata_ = new ::std::string;
  }
  configdata_->assign(value);
}
inline void Parameter::set_configdata(const char* value) {
  set_has_configdata();
  if (configdata_ == &::google::protobuf::internal::kEmptyString) {
    configdata_ = new ::std::string;
  }
  configdata_->assign(value);
}
inline void Parameter::set_configdata(const void* value, size_t size) {
  set_has_configdata();
  if (configdata_ == &::google::protobuf::internal::kEmptyString) {
    configdata_ = new ::std::string;
  }
  configdata_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Parameter::mutable_configdata() {
  set_has_configdata();
  if (configdata_ == &::google::protobuf::internal::kEmptyString) {
    configdata_ = new ::std::string;
  }
  return configdata_;
}
inline ::std::string* Parameter::release_configdata() {
  clear_has_configdata();
  if (configdata_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = configdata_;
    configdata_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Parameter::set_allocated_configdata(::std::string* configdata) {
  if (configdata_ != &::google::protobuf::internal::kEmptyString) {
    delete configdata_;
  }
  if (configdata) {
    set_has_configdata();
    configdata_ = configdata;
  } else {
    clear_has_configdata();
    configdata_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// resParameters

// repeated .protbuf.Parameter parameters = 1;
inline int resParameters::parameters_size() const {
  return parameters_.size();
}
inline void resParameters::clear_parameters() {
  parameters_.Clear();
}
inline const ::protbuf::Parameter& resParameters::parameters(int index) const {
  return parameters_.Get(index);
}
inline ::protbuf::Parameter* resParameters::mutable_parameters(int index) {
  return parameters_.Mutable(index);
}
inline ::protbuf::Parameter* resParameters::add_parameters() {
  return parameters_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protbuf::Parameter >&
resParameters::parameters() const {
  return parameters_;
}
inline ::google::protobuf::RepeatedPtrField< ::protbuf::Parameter >*
resParameters::mutable_parameters() {
  return &parameters_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protbuf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_parameters_2eproto__INCLUDED
